# version: "3"

services:
  broker:
    image: rabbitmq:3.13.5-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
      - 6000:1883
    volumes:
      - ./rbmq_image/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rbmq_image/conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rbmq_image/conf/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - custom_network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin  

  redis:
    image: redis:8-alpine
    container_name: redis
    volumes:
      - ./redis_image/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    networks:
      - custom_network

  db:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data/db:/var/lib/mysql
      - ./mysql_image:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  nginx:
    image: nginx:1.28.0
    container_name: nginx
    volumes:
      - ./nginx_image:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=haj-ebram.ir
      - NGINX_PORT=80

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24





